update

diff --git a/common/config/aliases b/common/config/aliases
--- a/common/config/aliases
+++ b/common/config/aliases
@@ -56,3 +56,27 @@ repo() {
     fi
     echo "finished"
 }
+
+ggupdate() {
+    untouched_repos=()
+    error_repos=()
+    for r in $(find . -maxdepth 1 -mindepth 1 -type d); do
+        cd $r
+        if [[ -d "./.git" ]]; then
+            current_branch=$(git rev-parse --abbrev-ref HEAD)
+            echo "currently in $r... $current_branch"
+            if [[ "$current_branch" =~ "master|develop" ]]; then
+                echo "pulling newest changes from $r"
+                { git fetch && ggpull; } || error_repos+=("$r")
+            else
+                untouched_repos+=("$r")
+            fi
+        fi
+        cd ..
+    done
+    echo "=====================\n"
+    echo "untouched repositories: $untouched_repos"
+    echo "=====================\n"
+    echo "failed to update repositories: $error_repos"
+}
+
